In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)

In [2]:
train= pd.read_csv('train.csv')
train

ID    YEAR   T2M_RANGE    T2M_MAX    T2M_MIN       RH2M         PS  \
0        0  1982.0 -241.552430  29.798545  13.691128  71.652934  89.725069   
1        1  1982.0 -241.819997  30.902708  15.298046  69.754933  89.865668   
2        2  1982.0 -241.883202  30.296561  14.660419  66.661416  89.846273   
3        3  1982.0 -242.007629  30.803224  15.246491  67.621173  90.029795   
4        4  1982.0 -240.659332  32.500906  15.303059  62.097329  89.825707   
...    ...     ...         ...        ...        ...        ...        ...   
1434  1434  2009.0 -246.654914  30.644813  20.268662  78.611410  89.333566   
1435  1435  2009.0 -247.651283  29.857874  20.425241  78.136636  89.324790   
1436  1436  2009.0 -247.594571  30.330303  21.123513  77.497787  89.334675   
1437  1437  2009.0 -247.083708  30.646652  20.883603  75.857655  89.465743   
1438  1438  2009.0 -246.099233  32.191877  21.121979  75.757341  89.528083   

         WS10M       QV2M        T2M  VACATION_RATE  
0     3.658959   8.474319  21.723403      64.184741  
1     3.529113   8.988374  22.911522      42.649137  
2     4.217007   8.474923  22.994887      52.819141  
3     4.484080   9.005508  23.594655      39.445489  
4     3.057211   8.307515  24.536776      46.444289  
...        ...        ...        ...            ...  
1434  6.433604  13.258977  26.685352       6.391643  
1435  7.638996  12.717079  25.991700       1.920453  
1436  8.939772  13.058350  26.619025       7.144639  
1437  7.663743  12.805387  26.923294       4.886901  
1438  6.426315  13.028215  27.318661      11.217462  

[1439 rows x 11 columns]

In [3]:
test=pd.read_csv('test.csv')
test

ID    YEAR   T2M_RANGE    T2M_MAX    T2M_MIN       RH2M         PS  \
0    1440  2009.0 -309.569706  32.919144  17.735611  74.415249  82.443918   
1    1441  2009.0 -310.763533  32.340370  17.955298  75.232482  82.320169   
2    1442  2009.0 -313.096292  29.670217  17.788919  80.950265  82.456590   
3    1443  2009.0 -312.110915  29.586632  16.777071  82.254238  82.460926   
4    1444  2009.0 -312.445008  30.088295  17.233512  81.311915  82.326908   
..    ...     ...         ...        ...        ...        ...        ...   
695  2135  2022.0 -310.857597  28.357413  15.023100  86.599317  82.511107   
696  2136  2022.0 -312.033878  26.943856  14.236847  85.965911  82.748450   
697  2137  2022.0 -312.869384  26.542410  14.972372  88.082615  82.626626   
698  2138  2022.0 -308.938303  27.599339  12.882619  84.585012  82.632252   
699  2139  2022.0 -310.589598  28.341680  14.604535  85.173914  82.874200   

        WS10M  
0    6.513046  
1    5.163099  
2    3.974139  
3    5.504794  
4    5.634695  
..        ...  
695  2.637025  
696  3.636588  
697  3.840101  
698  3.306362  
699  3.522586  

[700 rows x 8 columns]

In [4]:
X1_train=train.drop(['T2M','QV2M','VACATION_RATE'],axis=1)
X1_train

ID    YEAR   T2M_RANGE    T2M_MAX    T2M_MIN       RH2M         PS  \
0        0  1982.0 -241.552430  29.798545  13.691128  71.652934  89.725069   
1        1  1982.0 -241.819997  30.902708  15.298046  69.754933  89.865668   
2        2  1982.0 -241.883202  30.296561  14.660419  66.661416  89.846273   
3        3  1982.0 -242.007629  30.803224  15.246491  67.621173  90.029795   
4        4  1982.0 -240.659332  32.500906  15.303059  62.097329  89.825707   
...    ...     ...         ...        ...        ...        ...        ...   
1434  1434  2009.0 -246.654914  30.644813  20.268662  78.611410  89.333566   
1435  1435  2009.0 -247.651283  29.857874  20.425241  78.136636  89.324790   
1436  1436  2009.0 -247.594571  30.330303  21.123513  77.497787  89.334675   
1437  1437  2009.0 -247.083708  30.646652  20.883603  75.857655  89.465743   
1438  1438  2009.0 -246.099233  32.191877  21.121979  75.757341  89.528083   

         WS10M  
0     3.658959  
1     3.529113  
2     4.217007  
3     4.484080  
4     3.057211  
...        ...  
1434  6.433604  
1435  7.638996  
1436  8.939772  
1437  7.663743  
1438  6.426315  

[1439 rows x 8 columns]

In [5]:
y1_train=train["QV2M"]
y1_train

0        8.474319
1        8.988374
2        8.474923
3        9.005508
4        8.307515
          ...    
1434    13.258977
1435    12.717079
1436    13.058350
1437    12.805387
1438    13.028215
Name: QV2M, Length: 1439, dtype: float64

In [6]:
#to predict QV2M using train
regressor.fit(X1_train,y1_train)
pred1=regressor.predict(X1_train) 
pred1.round(1)

array([ 8.5,  9. ,  8.5, ..., 13.1, 12.8, 13. ])

In [7]:
y1_train.round(1)

0        8.5
1        9.0
2        8.5
3        9.0
4        8.3
        ... 
1434    13.3
1435    12.7
1436    13.1
1437    12.8
1438    13.0
Name: QV2M, Length: 1439, dtype: float64

In [8]:
accuracy=regressor.score(X1_train,y1_train)
accuracy

1.0

In [9]:
test

ID    YEAR   T2M_RANGE    T2M_MAX    T2M_MIN       RH2M         PS  \
0    1440  2009.0 -309.569706  32.919144  17.735611  74.415249  82.443918   
1    1441  2009.0 -310.763533  32.340370  17.955298  75.232482  82.320169   
2    1442  2009.0 -313.096292  29.670217  17.788919  80.950265  82.456590   
3    1443  2009.0 -312.110915  29.586632  16.777071  82.254238  82.460926   
4    1444  2009.0 -312.445008  30.088295  17.233512  81.311915  82.326908   
..    ...     ...         ...        ...        ...        ...        ...   
695  2135  2022.0 -310.857597  28.357413  15.023100  86.599317  82.511107   
696  2136  2022.0 -312.033878  26.943856  14.236847  85.965911  82.748450   
697  2137  2022.0 -312.869384  26.542410  14.972372  88.082615  82.626626   
698  2138  2022.0 -308.938303  27.599339  12.882619  84.585012  82.632252   
699  2139  2022.0 -310.589598  28.341680  14.604535  85.173914  82.874200   

        WS10M  
0    6.513046  
1    5.163099  
2    3.974139  
3    5.504794  
4    5.634695  
..        ...  
695  2.637025  
696  3.636588  
697  3.840101  
698  3.306362  
699  3.522586  

[700 rows x 8 columns]

In [10]:
y1_test=regressor.predict(test)
y1_test #T2M prediction on test.csv

array([11.70911996, 11.70911996, 11.43183516, 10.43781099, 10.43781099,
       10.43781099, 12.6820805 , 12.31240528, 10.43781099, 10.43781099,
       10.43781099, 10.43781099, 10.43781099, 10.43781099, 10.43781099,
       10.43781099, 10.43781099, 10.43781099, 10.43781099, 10.43781099,
       10.43781099, 10.43781099, 10.43781099, 10.43781099, 10.43781099,
       10.43781099, 10.43781099, 10.43781099, 10.43781099, 10.43781099,
       10.43781099, 11.70911996, 11.70911996, 10.43781099, 12.60991814,
       12.93719935, 13.09565434, 12.21978367, 12.21978367, 12.21978367,
       13.09565434, 12.60991814, 12.21978367, 12.21978367, 11.9947006 ,
       11.9947006 , 11.73293443, 11.70911996, 10.43781099, 11.9947006 ,
       10.43781099, 11.9947006 , 11.9947006 , 11.73293443, 11.90894873,
       11.90894873, 10.43781099, 10.43781099, 10.43781099, 10.43781099,
       10.43781099, 12.52439628, 12.52439628, 10.43781099, 10.43781099,
       10.43781099, 10.43781099, 10.43781099, 10.43781099, 10.43

In [11]:
accuracy=regressor.score(test,y1_test)
accuracy

1.0

In [12]:
test['QV2M']=y1_test #adding column to test dataset
test

ID    YEAR   T2M_RANGE    T2M_MAX    T2M_MIN       RH2M         PS  \
0    1440  2009.0 -309.569706  32.919144  17.735611  74.415249  82.443918   
1    1441  2009.0 -310.763533  32.340370  17.955298  75.232482  82.320169   
2    1442  2009.0 -313.096292  29.670217  17.788919  80.950265  82.456590   
3    1443  2009.0 -312.110915  29.586632  16.777071  82.254238  82.460926   
4    1444  2009.0 -312.445008  30.088295  17.233512  81.311915  82.326908   
..    ...     ...         ...        ...        ...        ...        ...   
695  2135  2022.0 -310.857597  28.357413  15.023100  86.599317  82.511107   
696  2136  2022.0 -312.033878  26.943856  14.236847  85.965911  82.748450   
697  2137  2022.0 -312.869384  26.542410  14.972372  88.082615  82.626626   
698  2138  2022.0 -308.938303  27.599339  12.882619  84.585012  82.632252   
699  2139  2022.0 -310.589598  28.341680  14.604535  85.173914  82.874200   

        WS10M       QV2M  
0    6.513046  11.709120  
1    5.163099  11.709120  
2    3.974139  11.431835  
3    5.504794  10.437811  
4    5.634695  10.437811  
..        ...        ...  
695  2.637025  10.437811  
696  3.636588  10.437811  
697  3.840101  10.437811  
698  3.306362  10.437811  
699  3.522586  10.437811  

[700 rows x 9 columns]

In [13]:
X2_train=train.drop(['T2M','VACATION_RATE'],axis=1)
X2_train

ID    YEAR   T2M_RANGE    T2M_MAX    T2M_MIN       RH2M         PS  \
0        0  1982.0 -241.552430  29.798545  13.691128  71.652934  89.725069   
1        1  1982.0 -241.819997  30.902708  15.298046  69.754933  89.865668   
2        2  1982.0 -241.883202  30.296561  14.660419  66.661416  89.846273   
3        3  1982.0 -242.007629  30.803224  15.246491  67.621173  90.029795   
4        4  1982.0 -240.659332  32.500906  15.303059  62.097329  89.825707   
...    ...     ...         ...        ...        ...        ...        ...   
1434  1434  2009.0 -246.654914  30.644813  20.268662  78.611410  89.333566   
1435  1435  2009.0 -247.651283  29.857874  20.425241  78.136636  89.324790   
1436  1436  2009.0 -247.594571  30.330303  21.123513  77.497787  89.334675   
1437  1437  2009.0 -247.083708  30.646652  20.883603  75.857655  89.465743   
1438  1438  2009.0 -246.099233  32.191877  21.121979  75.757341  89.528083   

         WS10M       QV2M  
0     3.658959   8.474319  
1     3.529113   8.988374  
2     4.217007   8.474923  
3     4.484080   9.005508  
4     3.057211   8.307515  
...        ...        ...  
1434  6.433604  13.258977  
1435  7.638996  12.717079  
1436  8.939772  13.058350  
1437  7.663743  12.805387  
1438  6.426315  13.028215  

[1439 rows x 9 columns]

In [14]:
y2_train=train["T2M"]
y2_train

0       21.723403
1       22.911522
2       22.994887
3       23.594655
4       24.536776
          ...    
1434    26.685352
1435    25.991700
1436    26.619025
1437    26.923294
1438    27.318661
Name: T2M, Length: 1439, dtype: float64

In [15]:
#to predict T2M using train
regressor.fit(X2_train,y2_train)
pred2=regressor.predict(X2_train) 
pred2

array([21.72340346, 22.91152202, 22.99488692, ..., 26.61902484,
       26.92329416, 27.3186611 ])

In [16]:
y2_train.round(0)

0       22.0
1       23.0
2       23.0
3       24.0
4       25.0
        ... 
1434    27.0
1435    26.0
1436    27.0
1437    27.0
1438    27.0
Name: T2M, Length: 1439, dtype: float64

In [17]:
accuracy=regressor.score(X2_train,y2_train)
accuracy

1.0

In [18]:
#T2M prediction on test.csv 
y2_test= regressor.predict(test)
test['T2M']=y2_test #adding T2M column to test
test

ID    YEAR   T2M_RANGE    T2M_MAX    T2M_MIN       RH2M         PS  \
0    1440  2009.0 -309.569706  32.919144  17.735611  74.415249  82.443918   
1    1441  2009.0 -310.763533  32.340370  17.955298  75.232482  82.320169   
2    1442  2009.0 -313.096292  29.670217  17.788919  80.950265  82.456590   
3    1443  2009.0 -312.110915  29.586632  16.777071  82.254238  82.460926   
4    1444  2009.0 -312.445008  30.088295  17.233512  81.311915  82.326908   
..    ...     ...         ...        ...        ...        ...        ...   
695  2135  2022.0 -310.857597  28.357413  15.023100  86.599317  82.511107   
696  2136  2022.0 -312.033878  26.943856  14.236847  85.965911  82.748450   
697  2137  2022.0 -312.869384  26.542410  14.972372  88.082615  82.626626   
698  2138  2022.0 -308.938303  27.599339  12.882619  84.585012  82.632252   
699  2139  2022.0 -310.589598  28.341680  14.604535  85.173914  82.874200   

        WS10M       QV2M        T2M  
0    6.513046  11.709120  26.049893  
1    5.163099  11.709120  26.049893  
2    3.974139  11.431835  24.436242  
3    5.504794  10.437811  24.099271  
4    5.634695  10.437811  24.099271  
..        ...        ...        ...  
695  2.637025  10.437811  22.499980  
696  3.636588  10.437811  22.499980  
697  3.840101  10.437811  22.499980  
698  3.306362  10.437811  20.518003  
699  3.522586  10.437811  22.499980  

[700 rows x 10 columns]

In [19]:
X3_train=train.drop('VACATION_RATE',axis=1)
X3_train

ID    YEAR   T2M_RANGE    T2M_MAX    T2M_MIN       RH2M         PS  \
0        0  1982.0 -241.552430  29.798545  13.691128  71.652934  89.725069   
1        1  1982.0 -241.819997  30.902708  15.298046  69.754933  89.865668   
2        2  1982.0 -241.883202  30.296561  14.660419  66.661416  89.846273   
3        3  1982.0 -242.007629  30.803224  15.246491  67.621173  90.029795   
4        4  1982.0 -240.659332  32.500906  15.303059  62.097329  89.825707   
...    ...     ...         ...        ...        ...        ...        ...   
1434  1434  2009.0 -246.654914  30.644813  20.268662  78.611410  89.333566   
1435  1435  2009.0 -247.651283  29.857874  20.425241  78.136636  89.324790   
1436  1436  2009.0 -247.594571  30.330303  21.123513  77.497787  89.334675   
1437  1437  2009.0 -247.083708  30.646652  20.883603  75.857655  89.465743   
1438  1438  2009.0 -246.099233  32.191877  21.121979  75.757341  89.528083   

         WS10M       QV2M        T2M  
0     3.658959   8.474319  21.723403  
1     3.529113   8.988374  22.911522  
2     4.217007   8.474923  22.994887  
3     4.484080   9.005508  23.594655  
4     3.057211   8.307515  24.536776  
...        ...        ...        ...  
1434  6.433604  13.258977  26.685352  
1435  7.638996  12.717079  25.991700  
1436  8.939772  13.058350  26.619025  
1437  7.663743  12.805387  26.923294  
1438  6.426315  13.028215  27.318661  

[1439 rows x 10 columns]

In [20]:
y3_train=train["VACATION_RATE"]
y3_train

0       64.184741
1       42.649137
2       52.819141
3       39.445489
4       46.444289
          ...    
1434     6.391643
1435     1.920453
1436     7.144639
1437     4.886901
1438    11.217462
Name: VACATION_RATE, Length: 1439, dtype: float64

In [21]:
#to predict using train
regressor.fit(X3_train,y3_train)
pred3=regressor.predict(X3_train) # VACATION RATE
pred3

array([64.18474085, 42.64913687, 52.81914124, ...,  7.14463862,
        4.88690149, 11.21746151])

In [22]:
y3_train[:10]

0    64.184741
1    42.649137
2    52.819141
3    39.445489
4    46.444289
5    29.495610
6    56.122047
7    71.968916
8    42.072725
9    19.738869
Name: VACATION_RATE, dtype: float64

In [23]:
y3_test=regressor.predict(test).astype(int)
test['VACATION_RATE']=y3_test
test

ID    YEAR   T2M_RANGE    T2M_MAX    T2M_MIN       RH2M         PS  \
0    1440  2009.0 -309.569706  32.919144  17.735611  74.415249  82.443918   
1    1441  2009.0 -310.763533  32.340370  17.955298  75.232482  82.320169   
2    1442  2009.0 -313.096292  29.670217  17.788919  80.950265  82.456590   
3    1443  2009.0 -312.110915  29.586632  16.777071  82.254238  82.460926   
4    1444  2009.0 -312.445008  30.088295  17.233512  81.311915  82.326908   
..    ...     ...         ...        ...        ...        ...        ...   
695  2135  2022.0 -310.857597  28.357413  15.023100  86.599317  82.511107   
696  2136  2022.0 -312.033878  26.943856  14.236847  85.965911  82.748450   
697  2137  2022.0 -312.869384  26.542410  14.972372  88.082615  82.626626   
698  2138  2022.0 -308.938303  27.599339  12.882619  84.585012  82.632252   
699  2139  2022.0 -310.589598  28.341680  14.604535  85.173914  82.874200   

        WS10M       QV2M        T2M  VACATION_RATE  
0    6.513046  11.709120  26.049893              0  
1    5.163099  11.709120  26.049893              0  
2    3.974139  11.431835  24.436242              3  
3    5.504794  10.437811  24.099271             13  
4    5.634695  10.437811  24.099271             13  
..        ...        ...        ...            ...  
695  2.637025  10.437811  22.499980             32  
696  3.636588  10.437811  22.499980             20  
697  3.840101  10.437811  22.499980             20  
698  3.306362  10.437811  20.518003             45  
699  3.522586  10.437811  22.499980             32  

[700 rows x 11 columns]

In [24]:
test1=test[['ID','VACATION_RATE']]

In [25]:
test1.to_csv('submission.csv', sep=',', index=False)
test1

ID  VACATION_RATE
0    1440              0
1    1441              0
2    1442              3
3    1443             13
4    1444             13
..    ...            ...
695  2135             32
696  2136             20
697  2137             20
698  2138             45
699  2139             32

[700 rows x 2 columns]

In [26]:
accuracy=regressor.score(X3_train,y3_train)
accuracy

1.0